package com.bridgelabz.sample;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class StatementExample {

	public static void main(String[] args) throws SQLException {
		// Statement stmt=null;
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		Connection connection = Utility.connections();
		int autoGeneratedID=0;
		// String query = "create table logindetails1 (user_id int(3) primary
		// key,user_name varchar(20),password varchar(16))";
		String query1 = "insert into logindetails values(?,?,?)";
		try {
			// stmt=connection.createStatement();
			// boolean rs=stmt.execute(query);
			// System.out.println(rs+" affected");

			// insert rows

			
			pstmt = connection.prepareStatement(query1);
			 autoGeneratedID=PreparedStatement.RETURN_GENERATED_KEYS;
			 pstmt.setInt(1, autoGeneratedID);
			
			System.out.println("Enter user name");
			String name = Utility.userInputString();
			pstmt.setString(2, name);

			System.out.println("Enter the password");
			String password = Utility.userInputString();
			boolean valid = Utility.validate(password);
			if (valid) {
				pstmt.setString(3, password);
			} else {
				System.out
						.println("password consists of upper, lower, special charecters,digits with minimum length 8");
			}
			pstmt.executeUpdate();

			/*rs = pstmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				System.out.println("Generated Emp Id: " + rs.getInt(1));
			}
*/
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			if (pstmt != null) {
				pstmt.close();
			}
			if (connection != null) {
				connection.close();
			}
		}
	}

}
